{
	"id": "00000000-0000-0000-d12f-00008fb7d087",
	"architectureId": 0,
	"baseProductName": "Microsoft Common Data Model SDK for Python",
	"baseProductVersion": "1.0.0",
	"baseScore": "6.5",
	"cpe": "cpe:2.3:a:microsoft:common_data_model_sdk_for_python:*:*:*:*:*:*:*:*",
	"customerActionRequired": true,
	"cveNumber": "CVE-2023-36566",
	"cweDetailsList": [
		{
			"keys": [
				"cwe",
				"cweUrl"
			],
			"values": [
				"CWE-20: Improper Input Validation",
				"https://cwe.mitre.org/data/definitions/20.html"
			]
		}
	],
	"cweList": [
		"CWE-20: Improper Input Validation"
	],
	"impact": "Denial of Service",
	"impactId": 100000001,
	"initialReleaseDate": "2023-10-10T07:00:00Z",
	"isMariner": false,
	"issuingCna": "Microsoft",
	"kbArticles": [
		{
			"affectedBinaries": [],
			"articleName": "Release Notes",
			"articleUrl": "https://github.com/microsoft/CDM",
			"downloadName": "Security Update",
			"downloadUrl": "https://pypi.org/project/commondatamodel-objectmodel/",
			"fixedBuildNumber": "1.7.4",
			"ordinal": 0,
			"rebootRequired": "Maybe"
		}
	],
	"platformId": 0,
	"product": "Microsoft Common Data Model SDK for Python",
	"productFamily": "Microsoft Dynamics",
	"productFamilyId": 100000006,
	"productId": 12241,
	"releaseDate": "2023-10-10T07:00:00Z",
	"releaseNumber": "2023-Oct",
	"severity": "Important",
	"severityId": 100000001,
	"temporalScore": "5.7",
	"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:N/I:N/A:H/E:U/RL:O/RC:C"
}
